Repository babel-plugin-ember-test-metadata/babel-plugin-ember-test-metadata-codemod, pull requests merged in 2021-11, with the labels that each got.

#1 Fixes invalid lockfile entries and removes node 10 support
  .github/workflows/ci.yml
  package.json
  transforms/setup-config/index.js
  transforms/setup-config/test.js
  yarn.lock
Labels: bug

#2 Add setup config transform
  transforms/setup-config/README.md
  transforms/setup-config/__testfixtures__/basic.input.js
  transforms/setup-config/__testfixtures__/basic.output.js
  transforms/setup-config/__testfixtures__/test-with-babel-property.input.js
  transforms/setup-config/__testfixtures__/test-with-babel-property.output.js
  transforms/setup-config/__testfixtures__/test-with-plugin-property.input.js
  transforms/setup-config/__testfixtures__/test-with-plugin-property.output.js
  transforms/setup-config/__testfixtures__/test-without-babel-property.input.js
  transforms/setup-config/__testfixtures__/test-without-babel-property.output.js
  transforms/setup-config/index.js
Labels: enhancement

#3 Fixing release-it setup
  CHANGELOG.md
  package.json
Labels: bug, internal

#4 add license
  package.json
Labels: internal

#5 Fix missing square brackets in plugin properties
  transforms/setup-config/__testfixtures__/test-already-setup.input.js
  transforms/setup-config/__testfixtures__/test-already-setup.output.js
  transforms/setup-config/__testfixtures__/test-with-babel-property.output.js
  transforms/setup-config/__testfixtures__/test-with-plugin-property.output.js
  transforms/setup-config/__testfixtures__/test-without-babel-property.output.js
  transforms/setup-config/index.js
Labels: bug
